Part1
ok-technopolis-autumn-2022/Vladislav_Pochernin pull request #1
Opened 2022-09-27 20:03 UTC by vspochernin

2022-09-29 06:47 UTC, fromanywhere requested changes
В этом коде я вижу теги div, h1, input и span

Если бы я делал эту задачку, у меня было бы в 3 раза больше

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +<html lang="en">
Здесь нет ошибки, но давайте лишний раз подумаем, будет ли аудитория Вашего приложения англоязычной

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +            <input type="submit" name="add-task-button">
Здесь нужно понять, какой функционал ожидается от этого контрола (вобще эта стрелка выбирает все / снимает все галки). Нужен ли тут сабмит? Что он будет сабмитить?

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +        <div class="task-list">
Нужно больше семантического разнообразия

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +                CSS
А как же функционал удаления?

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +                <input type="radio" name="display-mode" value="All">
Это хорошо

2022-09-29 06:47 UTC, fromanywhere commented on src/index.html
> +            <span class="right-block">Clear completed</span>
Тут должен быть не просто текст

2022-10-01 14:50 UTC, vspochernin commented on src/index.html
> +<html lang="en">
Я исходил из того, что [макет](https://www.figma.com/file/TNNpVRnLwDkUF4iUbap7wE/todo?node-id=0%3A1) написан на английском, соответственно, вероятно, аудитория будет использовать английский язык в качестве основного. 
Или же макеты всегда пишут на английском и это нам не говорит о том, какая будет аудитория?

2022-10-01 15:00 UTC, vspochernin commented on src/index.html
> +            <input type="submit" name="add-task-button">
Изначально думал, что стрелка работает, как нажатие клавиши "Enter" (то есть добавляет в список написанное дело). Если же стрелка выбирает/снимает выделение, думаю, что лучше сделать её обычной кнопкой : dbc25984b61cb812cbaf12069ab144d9fad1164d

2022-10-01 15:07 UTC, vspochernin commented on src/index.html
> +            <span class="right-block">Clear completed</span>
Изначально думал, что это просто надпись-лог, которая будет говорить, что, например, удаление прошло успешно. Как оказалось, это кнопка, которой можно удалить все завершенные задачи. Собственно, сделал её кнопкой: 82cfb9817429ad32fc18dba7b80368d4042ba5b3

2022-10-01 15:13 UTC, vspochernin commented on src/index.html
> +                CSS
Про него, к сожалению, забыл)
Думаю, что пока что просто кнопочек у каждой записи будет достаточно, а как их подвязать буду думать, когда начнем проходить JS: 9d031cf2f4f65927ad9a29b6bb2965b6fc1e2826

2022-10-01 18:37 UTC, vspochernin commented on src/index.html
> +        <div class="task-list">
Добавил семантическое разнообразие, а именно: 30821c918da455064906f437180b002d55657b8c
- Пометил заголовок страницы тегом ```<header>```.
- Пометил нижнюю часть страницы тегом ```<footer>```.
- Пометил основной контент (с которым будет взаимодействовать пользователь) тегом ```<main>```.
- Пометил поля ввода нового дела и сам список дел тегом ```<section>```.
- Пометил каждое конкретное дело тегом ```<article>```.

2022-10-01 18:47 UTC, vspochernin commented on src/index.html
> +        <div class="task-list">
Один момент для меня сомнительный: быть может лучше на сам список дел поставтить ```<ul>``` вместо ```<section>```, а на каждое дело ```<li>``` вместо ```<article>```?

2022-10-03 07:55 UTC, fromanywhere commented on src/index.html
> +<html lang="en">
Да. Макет Вам может нарисовать какой-нибудь дизайнер на аутсорсе, который не подумал (или для которого латиница просто эстетиченее выглядит). Здесь Вам нужно думать, не как исполнителю, а как продуктовому разработчику — какую задачу вы решаете и для кого

2022-10-03 07:56 UTC, fromanywhere commented on src/index.html
> +            <input type="submit" name="add-task-button">
👍

2022-10-03 07:57 UTC, fromanywhere commented on src/index.html
> +        <div class="task-list">
Верно, это список. Сегодня Вам расскажут, почему это имеет смысл

2022-10-03 07:57 UTC, fromanywhere commented on src/index.html
> +                CSS
👍

2022-10-03 07:57 UTC, fromanywhere commented on src/index.html
> +            <span class="right-block">Clear completed</span>
👍

2022-10-06 11:08 UTC, vspochernin commented on src/index.html
> +<html lang="en">
Я решил, что приложение будет ориентированно на русскоговорящую аудиторию, поэтому изменил язык: 779b2a445f17528a9749d470ac10e352683db141

2022-10-06 11:08 UTC, vspochernin commented on src/index.html
> +        <div class="task-list">
Так как это последний комментарий, который нужно закрыть, я опишу здесь все, что доделал в рамках улучшения этой части задания:
- Добавил ненумерованный список: fe839e21c82f6923d55c92c560095160d2534d8b
- Поставил выбранной галочку на "Все" по умолчанию: 8e37c4f8bd00b1258348e3a609152d7337cb0032
- Добавил лейблы для радио-кнопок: b58abcab940093f07d3837bc1d5af205035bb992
- Добавил accessibility: aaad15a34db73398e2ad49dac12c88e9b95c60b8

2022-10-06 12:56 UTC, fromanywhere requested changes

2022-10-06 12:56 UTC, fromanywhere commented on src/index.html
> +            <input type="button" name="toggle-select-all-button" aria-label="Отметить все задачи">
name не нужен, я бы заменил на всех кнопках с иконками aria-label на title

2022-10-06 12:56 UTC, fromanywhere commented on src/index.html
> +            <span class="middle-block">
тут имеет смысл добавить role (какую?) и заголовок к ней через aria-label

2022-10-07 18:41 UTC, vspochernin commented on src/index.html
> +            <input type="button" name="toggle-select-all-button" aria-label="Отметить все задачи">
Удалил лишние `name` и заменил `aria-label` на `title` на кнопках с иконками: 47cf0b82c5e9cda9075974f20f3c9ed02c14023c

2022-10-07 18:41 UTC, vspochernin commented on src/index.html
> +            <span class="middle-block">
Я думаю, что лучше всего подойдет `role="radiogroup` и `aria-label="Выбор режима отображения"`: b47aded7ed4479821d44c105129f47ecab868683

Также мне понравился нейминг классов из презентации и я попробовал сразу сделать БЭМ здесь, чтобы было легче настраивать CSS стили и не переделывать этот момент потом: ae760cab695a2ba7bc712057600240afc3c77282
Подскажите, пожалуйста, подойдет ли такой нейминг, как у меня?

2022-10-08 11:17 UTC, fromanywhere approved these changes

2022-10-08 11:17 UTC, fromanywhere commented on src/index.html
> +            <span class="middle-block">
Нейминг ок
про это будет отдельная лекция еще

2022-10-08 11:55 UTC, merged