Part2: CSS
ok-technopolis-autumn-2022/Vladislav_Pochernin pull request #2
Opened 2022-10-16 18:06 UTC by vspochernin

Начал разбираться с CSS (в основном, конечно, с макетом). Пока до идеала далеко, но (вроде) на оригинал начинает быть похожим.
После лекции в понедельник буду продолжать доводить до идеала, но мб уже сейчас есть явные вещи, которые поправить надо, поэтому публикую PR.

2022-10-17 07:55 UTC, fromanywhere requested changes
С точки зрения базовой структуры неплохо — весь макет нормально проходится табом, подсветка не теряется. Сейчас главное, над чем нужно подумать — что будет, если элементов в списке будет значительно больше

2022-10-17 07:55 UTC, fromanywhere commented on src/styles/style.css
> +    transform: translate(-50%, -50%);
я бы не рекомендовал центрировать таким способом без крайней необходимости. Возьмите тут лучше флекс или выровняйте через margin

2022-10-17 07:55 UTC, fromanywhere commented on src/styles/style.css
> +    flex-grow: 10;
1 будет достаточно

2022-10-17 08:59 UTC, vspochernin commented
Насчет большого количества элементов - что думаете о таком решении: 2cf59b5ce451262d831ad908b6af8368a522900c
Я убрал жесткое ограничение по высоте заменил его `flex-basis`'ом.
Теперь, если у нас только 4 элемента, список выглядит так: 
![image](https://user-images.githubusercontent.com/20515939/196134933-fb111fe5-1e7a-4fc8-8652-ccf7aff85b1b.png)
Добавим туда кучу элементов и он растянется:
![image](https://user-images.githubusercontent.com/20515939/196135049-da7e622c-1b7a-4ec5-8a8e-528f1a87dc9b.png)
Удалим все элементы, тудушка будет базовой длины:
![image](https://user-images.githubusercontent.com/20515939/196135190-1b633691-afb8-40a0-99fc-b9bc028c6c6b.png)

2022-10-17 08:59 UTC, vspochernin commented on src/styles/style.css
> +    flex-grow: 10;
Исправил: 3db058a7706a57ac8dd70cbf5834fb164d5934dd

2022-10-17 08:59 UTC, vspochernin commented on src/styles/style.css
> +    transform: translate(-50%, -50%);
Исправил: af97ce62e93b1fb9e6c566f18293ca1d56ed7ed1

2022-10-17 09:07 UTC, fromanywhere commented
Концептуально направление мысли верное, но я бы брал min-height

2022-10-17 09:15 UTC, vspochernin commented
Заменил `flex-basis` на `min-height`: 503dfcdec9d4ee53420d0096b04ecee3e8fbce9f

2022-10-20 23:42 UTC, vspochernin commented
Обновил стили. Кажется, довел внешний вид до ума но есть проблема:
То, как я реализовал появление кнопок удаление только при наведении на задачу почему-то не дает их нажимать. Т.е. крестик никак не реагирует на нажатия (проверял, добавив стиль с псевдоклассом `active`, при этом остальные кнопки реагировали). Быть может мне не реализовывать сейчас эту функциональность (сокрытие крестика удаления, если не наведено на задачу) и это будет как-то с помощью JS делаться уже?

2022-10-21 06:50 UTC, fromanywhere commented
Нет, весь визуал делаем стилями

2022-10-21 06:53 UTC, fromanywhere commented
Посмотрел код, весьма похоже на правду, есть несколько визуальных ошибок при навигации с клавиатуры. Сегодня наскриншочу

2022-10-21 15:52 UTC, vspochernin commented
> Нет, весь визуал делаем стилями

Тогда и зачеркивание можно сделать в стилях? Нам просто (вроде) говорили, что лучше в JS класс вешать на текст, когда нажал отмеченным

2022-10-21 16:24 UTC, fromanywhere commented
Мы в Вами можем договориться, что для зачеркивания Вы будете вешать класс. Я просто хочу видеть, что работа с checked проведена

2022-10-21 16:40 UTC, vspochernin commented
Хорошо, тогда я попробую это сделать с помощью JS

2022-10-21 22:02 UTC, fromanywhere requested changes
Все шансы сдать домашку

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    margin: 250px;
Это неудачно. 
<img width="1903" alt="Снимок экрана 2022-10-22 в 00 45 03" src="https://user-images.githubusercontent.com/1042969/197294177-2d9f4c33-f841-4100-a4b1-bf996a85875e.png">

Попробуйте лучше растянуть на всю высоту, н-р
```
min-height: 100vh;
margin: 0;
```

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    letter-spacing: -0.6000000238418579px;
я бы не использовал это свойство, не говоря уже о точности округления

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    justify-content: space-between;
на самом деле это не нужно

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    box-shadow: 0px -1px 0px 0px #E6E6E6 inset;
тут предполагался border — figma врет

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    margin-right: auto;
на самом деле тут должен быть flex-grow: 1

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +.task-item:hover > .task-item__delete {
тут нужно подумать, еще про фокус, иначе с клавиатуры так
<img width="123" alt="Снимок экрана 2022-10-22 в 00 57 17" src="https://user-images.githubusercontent.com/1042969/197294668-b8fb3839-a55d-4eec-9edd-d5a50b5428e4.png">

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    width: 20px;
Увеличьте площадь, чтобы не приходилось целиться мышкой

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    width: 26px;
Увеличьте площадь, чтобы не приходилось целиться мышкой

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    border: 2px solid #EBDFDF;
Нужно подумать, чтобы не прыгало

https://user-images.githubusercontent.com/1042969/197294856-3289dbf4-0869-43ce-a5f1-8448382a69ce.mov

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    content: "";
лучше псевдоэлементом
но если совсем никак, то content не нужен

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    box-shadow: 0px -1px 0px 0px #E6E6E6 inset;
тут бордер

2022-10-21 22:02 UTC, fromanywhere commented on src/styles/style.css
> +    box-shadow: 0px 1px 0px 0px #E6E6E6 inset;
тут бордер

2022-10-23 20:55 UTC, vspochernin commented on src/styles/style.css
> +    margin: 250px;
Исправил: 6d8d98e72438e6f062d197ce5dbe35a64aba164d

2022-10-23 20:59 UTC, vspochernin commented on src/styles/style.css
> +    letter-spacing: -0.6000000238418579px;
Удалил: fd916ef8e0d5ee47d5d463af7abfe1eb9efbb257

2022-10-23 20:59 UTC, vspochernin commented on src/styles/style.css
> +    justify-content: space-between;
Действительно. Удалил: 32cb62d7633a12f4a2a5dbe09a9ad41595969779

2022-10-23 20:59 UTC, vspochernin commented on src/styles/style.css
> +    box-shadow: 0px -1px 0px 0px #E6E6E6 inset;
Удалил лишние box-shadow и поставил, где нужно border: 283ff46271f681647b65c06047f7340b2cd71250

2022-10-23 21:00 UTC, vspochernin commented on src/styles/style.css
> +    margin-right: auto;
Исправил: 1fd3033fc8f1bcaf1d80f3c40338b88a9da51c1a

2022-10-23 21:00 UTC, vspochernin commented on src/styles/style.css
> +.task-item:hover > .task-item__delete {
Добавил те же правила к фокусу кнопки: ccf0da6b13eb25404cd578d6bc3e23309eafa032

2022-10-23 21:00 UTC, vspochernin commented on src/styles/style.css
> +    width: 20px;
Увеличил площадь, а также, немного поменял цвет фона, чтобы он подходил под общий фон: c28521e625a46385261485600f182665c747825d

2022-10-23 21:00 UTC, vspochernin commented on src/styles/style.css
> +    width: 26px;
Увеличил: 13308ca6ac6b1dc1c81080270be7cf0b5755991c

2022-10-23 21:01 UTC, vspochernin commented on src/styles/style.css
> +    border: 2px solid #EBDFDF;
Возможно, это костыль, но я придумал просто сделать бордер в 1 пиксель по умолчанию: 0b495d00e92419c3c58a16d5d8cc052505082047
Соответственно, бордер всегда есть и он просто меняет цвет при переводе выбора

2022-10-23 21:01 UTC, vspochernin commented on src/styles/style.css
> +    content: "";
Изначально я пытался это сделать через псевдоэлементы `::before` и `::after`, удавалось спозиционировать `::after`, но вот `::before` никак не поддавался. Решил сделать просто два элемента. Вроде, это не должно помешать дальнейшей работе.
Удалил content: 990cad669dd7b57ed12c04f1bc5f0418cdb8877a

2022-10-23 21:01 UTC, vspochernin commented on src/styles/style.css
> +    box-shadow: 0px -1px 0px 0px #E6E6E6 inset;
Удалил лишние box-shadow и поставил, где нужно border: 283ff46271f681647b65c06047f7340b2cd71250

2022-10-23 21:01 UTC, vspochernin commented on src/styles/style.css
> +    box-shadow: 0px 1px 0px 0px #E6E6E6 inset;
Удалил лишние box-shadow и поставил, где нужно border: 283ff46271f681647b65c06047f7340b2cd71250

2022-10-24 07:48 UTC, fromanywhere commented on src/styles/style.css
> +    border: 2px solid #EBDFDF;
да, это хорошо

2022-10-24 07:49 UTC, fromanywhere approved these changes

2022-10-24 07:55 UTC, merged